/* ===== Scratchito · Definición de bloques (réplica de Scratch 3.0 en español) =====
   shape: hat | stack | cap | c | c2 | reporter | boolean
   spec:  L(texto) | N(num) | T(texto libre) | M(menú) | B(hueco booleano) | S(hueco valor) | C(color)
*/
const L = v => ({t:'label', v});
const N = (k,d) => ({t:'num', k, d});
const T = (k,d) => ({t:'text', k, d});
const M = (k,opts,d) => ({t:'menu', k, opts, d: d ?? opts[0]});
const B = k => ({t:'bool', k});
const C = (k,d='#ff0000') => ({t:'color', k, d});

const DIRS = ['derecha (90)','izquierda (-90)','arriba (0)','abajo (180)'];
const KEYS = ['espacio','flecha arriba','flecha abajo','flecha derecha','flecha izquierda','cualquiera',
  'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
  '0','1','2','3','4','5','6','7','8','9'];

const CATS = [
  {id:'motion',    name:'Movimiento', color:'#4C97FF', icon:'motion'},
  {id:'looks',     name:'Apariencia', color:'#9966FF', icon:'looks'},
  {id:'sound',     name:'Sonido',     color:'#CF63CF', icon:'speaker'},
  {id:'events',    name:'Eventos',    color:'#FFBF00', icon:'events'},
  {id:'control',   name:'Control',    color:'#FFAB19', icon:'control'},
  {id:'sensing',   name:'Sensores',   color:'#5CB1D6', icon:'sensing'},
  {id:'operators', name:'Operadores', color:'#59C059', icon:'operators'},
  {id:'variables', name:'Variables',  color:'#FF8C1A', icon:'variables'},
  {id:'myblocks',  name:'Mis bloques',color:'#FF6680', icon:'pen'}
];

const BLOCKS = {
/* ---------------- MOVIMIENTO ---------------- */
 mover:        {cat:'motion', shape:'stack', spec:[L('mover'),N('pasos',10),L('pasos')]},
 girarD:       {cat:'motion', shape:'stack', spec:[L('girar @rot-cw'),N('g',15),L('grados')]},
 girarI:       {cat:'motion', shape:'stack', spec:[L('girar @rot-ccw'),N('g',15),L('grados')]},
 irA:          {cat:'motion', shape:'stack', spec:[L('ir a x:'),N('x',0),L('y:'),N('y',0)]},
 irAObj:       {cat:'motion', shape:'stack', spec:[L('ir a'),M('destino',['posición aleatoria','puntero del ratón'])]},
 deslizar:     {cat:'motion', shape:'stack', spec:[L('deslizar en'),N('s',1),L('segs a x:'),N('x',0),L('y:'),N('y',0)]},
 apuntarA:     {cat:'motion', shape:'stack', spec:[L('apuntar en dirección'),N('dir',90)]},
 apuntarHacia: {cat:'motion', shape:'stack', spec:[L('apuntar hacia'),M('destino',['puntero del ratón'])]},
 cambiarX:     {cat:'motion', shape:'stack', spec:[L('cambiar x por'),N('v',10)]},
 fijarX:       {cat:'motion', shape:'stack', spec:[L('fijar x a'),N('v',0)]},
 cambiarY:     {cat:'motion', shape:'stack', spec:[L('cambiar y por'),N('v',10)]},
 fijarY:       {cat:'motion', shape:'stack', spec:[L('fijar y a'),N('v',0)]},
 rebotar:      {cat:'motion', shape:'stack', spec:[L('si toca un borde, rebotar')]},
 estiloRot:    {cat:'motion', shape:'stack', spec:[L('fijar estilo de rotación'),M('estilo',['izquierda-derecha','no rotar','todo alrededor'])]},
 irADeslizando:{cat:'motion', shape:'stack', spec:[L('deslizar en'),N('s',1),L('segs a'),M('destino',['posición aleatoria','puntero del ratón'])]},
 moverHacia:   {cat:'motion', shape:'stack', spec:[L('mover'),N('pasos',10),L('pasos hacia'),M('destino',['puntero del ratón','@objetos'])]},
 apuntarObj:   {cat:'motion', shape:'stack', spec:[L('apuntar hacia el objeto'),M('obj',['@objetos'])]},
 cambiarXY:    {cat:'motion', shape:'stack', spec:[L('cambiar x por'),N('x',10),L('e y por'),N('y',10)]},
 rebotarSuave: {cat:'motion', shape:'stack', spec:[L('rebotar con velocidad'),N('v',5),L('en x'),N('vx',3)]},
 ponerEnBorde: {cat:'motion', shape:'stack', spec:[L('colocar en el borde'),M('borde',['superior','inferior','izquierdo','derecho'])]},
 distanciaXY:  {cat:'motion', shape:'reporter', spec:[L('distancia al punto x:'),N('x',0),L('y:'),N('y',0)]},
 posX:         {cat:'motion', shape:'reporter', spec:[L('posición en x')]},
 posY:         {cat:'motion', shape:'reporter', spec:[L('posición en y')]},
 direccion:    {cat:'motion', shape:'reporter', spec:[L('dirección')]},

/* ---------------- APARIENCIA ---------------- */
 decirPor:     {cat:'looks', shape:'stack', spec:[L('decir'),T('msg','¡Hola!'),L('por'),N('s',2),L('segundos')]},
 decir:        {cat:'looks', shape:'stack', spec:[L('decir'),T('msg','¡Hola!')]},
 pensarPor:    {cat:'looks', shape:'stack', spec:[L('pensar'),T('msg','Mmm...'),L('por'),N('s',2),L('segundos')]},
 pensar:       {cat:'looks', shape:'stack', spec:[L('pensar'),T('msg','Mmm...')]},
 cambiarDisfraz:{cat:'looks', shape:'stack', spec:[L('cambiar disfraz a'),M('disfraz',['@disfraces'])]},
 siguienteDisfraz:{cat:'looks', shape:'stack', spec:[L('siguiente disfraz')]},
 cambiarFondo: {cat:'looks', shape:'stack', spec:[L('cambiar fondo a'),M('fondo',['@fondos'])]},
 siguienteFondo:{cat:'looks', shape:'stack', spec:[L('siguiente fondo')]},
 cambiarTam:   {cat:'looks', shape:'stack', spec:[L('cambiar tamaño por'),N('v',10)]},
 fijarTam:     {cat:'looks', shape:'stack', spec:[L('fijar tamaño al'),N('v',100),L('%')]},
 cambiarEfecto:{cat:'looks', shape:'stack', spec:[L('cambiar efecto'),M('ef',['color','ojo de pez','remolino','pixelar','brillo','fantasma']),L('por'),N('v',25)]},
 fijarEfecto:  {cat:'looks', shape:'stack', spec:[L('fijar efecto'),M('ef',['color','ojo de pez','remolino','pixelar','brillo','fantasma']),L('a'),N('v',0)]},
 quitarEfectos:{cat:'looks', shape:'stack', spec:[L('quitar efectos gráficos')]},
 mostrar:      {cat:'looks', shape:'stack', spec:[L('mostrar')]},
 esconder:     {cat:'looks', shape:'stack', spec:[L('esconder')]},
 alFrente:     {cat:'looks', shape:'stack', spec:[L('ir a capa'),M('capa',['frontal','trasera'])]},
 disfrazAnterior:{cat:'looks', shape:'stack', spec:[L('disfraz anterior')]},
 disfrazAzar:  {cat:'looks', shape:'stack', spec:[L('disfraz al azar')]},
 fondoAzar:    {cat:'looks', shape:'stack', spec:[L('fondo al azar')]},
 cambiarCapas: {cat:'looks', shape:'stack', spec:[L('cambiar'),N('n',1),L('capas hacia'),M('dir',['adelante','atrás'])]},
 parpadear:    {cat:'looks', shape:'stack', spec:[L('parpadear'),N('n',3),L('veces')]},
 rebotarTam:   {cat:'looks', shape:'stack', spec:[L('efecto rebote de tamaño')]},
 nombreDisfraz:{cat:'looks', shape:'reporter', spec:[L('nombre del disfraz')]},
 nombreFondo:  {cat:'looks', shape:'reporter', spec:[L('nombre del fondo')]},
 numFondo:     {cat:'looks', shape:'reporter', spec:[L('número de fondo')]},
 estaVisible:  {cat:'looks', shape:'boolean', spec:[L('¿está visible?')]},
 numDisfraz:   {cat:'looks', shape:'reporter', spec:[L('número de disfraz')]},
 tamano:       {cat:'looks', shape:'reporter', spec:[L('tamaño')]},

/* ---------------- SONIDO ---------------- */
 tocarSonidoHasta:{cat:'sound', shape:'stack', spec:[L('tocar sonido'),M('snd',['@sonidos']),L('hasta que termine')]},
 tocarSonido:  {cat:'sound', shape:'stack', spec:[L('iniciar sonido'),M('snd',['@sonidos'])]},
 pararSonidos: {cat:'sound', shape:'stack', spec:[L('detener todos los sonidos')]},
 tocarNota:    {cat:'sound', shape:'stack', spec:[L('tocar nota'),N('nota',60),L('por'),N('s',0.5),L('segundos')]},
 cambiarVol:   {cat:'sound', shape:'stack', spec:[L('cambiar volumen por'),N('v',-10)]},
 fijarVol:     {cat:'sound', shape:'stack', spec:[L('fijar volumen al'),N('v',100),L('%')]},
 tocarMelodia: {cat:'sound', shape:'stack', spec:[L('tocar melodía'),M('mel',['alegre','triste','victoria','misterio','fanfarria'])]},
 tocarTambor:  {cat:'sound', shape:'stack', spec:[L('tocar tambor'),M('t',['bombo','caja','platillo','tom','palmada']),L('por'),N('s',0.25),L('segundos')]},
 silencio:     {cat:'sound', shape:'stack', spec:[L('silencio por'),N('s',0.25),L('segundos')]},
 cambiarTono:  {cat:'sound', shape:'stack', spec:[L('cambiar tono por'),N('v',10),L('semitonos')]},
 fijarTono:    {cat:'sound', shape:'stack', spec:[L('fijar tono a'),N('v',0),L('semitonos')]},
 tono:         {cat:'sound', shape:'reporter', spec:[L('tono')]},
 volumen:      {cat:'sound', shape:'reporter', spec:[L('volumen')]},

/* ---------------- EVENTOS ---------------- */
 alBandera:    {cat:'events', shape:'hat', spec:[L('al hacer clic en Ejecutar')]},
 alTecla:      {cat:'events', shape:'hat', spec:[L('al presionar tecla'),M('tecla',KEYS,'espacio')]},
 alClicObjeto: {cat:'events', shape:'hat', spec:[L('al hacer clic en este objeto')]},
 alFondo:      {cat:'events', shape:'hat', spec:[L('al cambiar el fondo a'),M('fondo',['@fondos'])]},
 alRecibir:    {cat:'events', shape:'hat', spec:[L('al recibir'),M('msg',['mensaje1'])]},
 enviar:       {cat:'events', shape:'stack', spec:[L('enviar'),M('msg',['mensaje1'])]},
 enviarEsperar:{cat:'events', shape:'stack', spec:[L('enviar'),M('msg',['mensaje1']),L('y esperar')]},
 alTocarObj:   {cat:'events', shape:'hat', spec:[L('al tocar'),M('obj',['puntero del ratón','borde','@objetos'])]},
 alMayorQue:   {cat:'events', shape:'hat', spec:[L('cuando'),M('q',['cronómetro','volumen del micro']),L('>'),N('v',10)]},
 alCargar:     {cat:'events', shape:'hat', spec:[L('al cargar el proyecto')]},
 mensajeRecibido:{cat:'events', shape:'reporter', spec:[L('último mensaje')]},

/* ---------------- CONTROL ---------------- */
 esperar:      {cat:'control', shape:'stack', spec:[L('esperar'),N('s',1),L('segundos')]},
 repetir:      {cat:'control', shape:'c', spec:[L('repetir'),N('n',10)]},
 porSiempre:   {cat:'control', shape:'c', cap:true, spec:[L('por siempre')]},
 si:           {cat:'control', shape:'c', spec:[L('si'),B('cond'),L('entonces')]},
 siSino:       {cat:'control', shape:'c2', spec:[L('si'),B('cond'),L('entonces')], spec2:[L('si no')]},
 esperarHasta: {cat:'control', shape:'stack', spec:[L('esperar hasta que'),B('cond')]},
 repetirHasta: {cat:'control', shape:'c', spec:[L('repetir hasta que'),B('cond')]},
 detener:      {cat:'control', shape:'cap', spec:[L('detener'),M('q',['todos','este programa','otros programas del objeto'])]},
 alClonar:     {cat:'control', shape:'hat', spec:[L('al comenzar como clon')]},
 crearClon:    {cat:'control', shape:'stack', spec:[L('crear clon de'),M('obj',['mí mismo'])]},
 borrarClon:   {cat:'control', shape:'cap', spec:[L('eliminar este clon')]},
 repetirDesde: {cat:'control', shape:'c', spec:[L('contar desde'),N('a',1),L('hasta'),N('b',10)]},
 mientras:     {cat:'control', shape:'c', spec:[L('mientras'),B('cond')]},
 siNoEntonces: {cat:'control', shape:'c', spec:[L('si NO'),B('cond'),L('entonces')]},
 esperarFrames:{cat:'control', shape:'stack', spec:[L('esperar'),N('n',1),L('fotogramas')]},
 contador:     {cat:'control', shape:'reporter', spec:[L('contador del bucle')]},

/* ---------------- SENSORES ---------------- */
 tocando:      {cat:'sensing', shape:'boolean', spec:[L('¿tocando'),M('obj',['puntero del ratón','borde','@objetos']),L('?')]},
 tocandoColor: {cat:'sensing', shape:'boolean', spec:[L('¿tocando el color'),C('col'),L('?')]},
 distanciaA:   {cat:'sensing', shape:'reporter', spec:[L('distancia a'),M('obj',['puntero del ratón','@objetos'])]},
 preguntar:    {cat:'sensing', shape:'stack', spec:[L('preguntar'),T('q','¿Cómo te llamas?'),L('y esperar')]},
 respuesta:    {cat:'sensing', shape:'reporter', spec:[L('respuesta')]},
 teclaPulsada: {cat:'sensing', shape:'boolean', spec:[L('¿tecla'),M('tecla',KEYS,'espacio'),L('presionada?')]},
 ratonAbajo:   {cat:'sensing', shape:'boolean', spec:[L('¿ratón presionado?')]},
 ratonX:       {cat:'sensing', shape:'reporter', spec:[L('x del ratón')]},
 ratonY:       {cat:'sensing', shape:'reporter', spec:[L('y del ratón')]},
 cronometro:   {cat:'sensing', shape:'reporter', spec:[L('cronómetro')]},
 reiniciarCrono:{cat:'sensing', shape:'stack', spec:[L('reiniciar cronómetro')]},
 fechaActual:  {cat:'sensing', shape:'reporter', spec:[L('valor actual de'),M('u',['año','mes','día','hora','minuto','segundo'])]},
 tocandoBorde: {cat:'sensing', shape:'boolean', spec:[L('¿tocando el borde'),M('b',['cualquiera','superior','inferior','izquierdo','derecho']),L('?')]},
 clicEnMi:     {cat:'sensing', shape:'boolean', spec:[L('¿clic sobre mí?')]},
 propiedadDe:  {cat:'sensing', shape:'reporter', spec:[M('prop',['posición en x','posición en y','dirección','tamaño','número de disfraz']),L('de'),M('obj',['@objetos'])]},
 anchoEscenario:{cat:'sensing', shape:'reporter', spec:[L('ancho del escenario')]},
 altoEscenario:{cat:'sensing', shape:'reporter', spec:[L('alto del escenario')]},
 numObjetos:   {cat:'sensing', shape:'reporter', spec:[L('cantidad de objetos')]},
 esMovil:      {cat:'sensing', shape:'boolean', spec:[L('¿es un móvil?')]},

/* ---------------- OPERADORES ---------------- */
 sumar:        {cat:'operators', shape:'reporter', spec:[S('a'),L('+'),S('b')]},
 restar:       {cat:'operators', shape:'reporter', spec:[S('a'),L('−'),S('b')]},
 multiplicar:  {cat:'operators', shape:'reporter', spec:[S('a'),L('×'),S('b')]},
 dividir:      {cat:'operators', shape:'reporter', spec:[S('a'),L('/'),S('b')]},
 azar:         {cat:'operators', shape:'reporter', spec:[L('número aleatorio entre'),N('a',1),L('y'),N('b',10)]},
 mayor:        {cat:'operators', shape:'boolean', spec:[S('a',''),L('>'),S('b','50')]},
 menor:        {cat:'operators', shape:'boolean', spec:[S('a',''),L('<'),S('b','50')]},
 igual:        {cat:'operators', shape:'boolean', spec:[S('a',''),L('='),S('b','50')]},
 y:            {cat:'operators', shape:'boolean', spec:[B('a'),L('y'),B('b')]},
 o:            {cat:'operators', shape:'boolean', spec:[B('a'),L('o'),B('b')]},
 no:           {cat:'operators', shape:'boolean', spec:[L('no'),B('a')]},
 unir:         {cat:'operators', shape:'reporter', spec:[L('unir'),S('a','manza'),S('b','na')]},
 letraDe:      {cat:'operators', shape:'reporter', spec:[L('letra'),N('n',1),L('de'),S('s','manzana')]},
 largoDe:      {cat:'operators', shape:'reporter', spec:[L('largo de'),S('s','manzana')]},
 contiene:     {cat:'operators', shape:'boolean', spec:[S('a','manzana'),L('contiene'),S('b','a'),L('?')]},
 modulo:       {cat:'operators', shape:'reporter', spec:[S('a','7'),L('mod'),S('b','3')]},
 redondear:    {cat:'operators', shape:'reporter', spec:[L('redondear'),S('a','3.7')]},
 mateDe:       {cat:'operators', shape:'reporter', spec:[M('f',['abs','piso','techo','raíz','sin','cos','tan','ln','log','e^','10^']),L('de'),S('a','9')]},
 mayorIgual:   {cat:'operators', shape:'boolean', spec:[S('a',''),L('≥'),S('b','50')]},
 menorIgual:   {cat:'operators', shape:'boolean', spec:[S('a',''),L('≤'),S('b','50')]},
 distinto:     {cat:'operators', shape:'boolean', spec:[S('a',''),L('≠'),S('b','50')]},
 entre:        {cat:'operators', shape:'boolean', spec:[S('a','5'),L('está entre'),S('b','1'),L('y'),S('c','10')]},
 potencia:     {cat:'operators', shape:'reporter', spec:[S('a','2'),L('elevado a'),S('b','3')]},
 minimo:       {cat:'operators', shape:'reporter', spec:[L('mínimo entre'),S('a','5'),L('y'),S('b','9')]},
 maximo:       {cat:'operators', shape:'reporter', spec:[L('máximo entre'),S('a','5'),L('y'),S('b','9')]},
 limitar:      {cat:'operators', shape:'reporter', spec:[L('limitar'),S('a','15'),L('entre'),S('b','0'),L('y'),S('c','10')]},
 mayusculas:   {cat:'operators', shape:'reporter', spec:[M('caso',['MAYÚSCULAS','minúsculas']),L('de'),S('s','Hola')]},
 reemplazar:   {cat:'operators', shape:'reporter', spec:[L('en'),S('s','manzana'),L('cambiar'),S('a','a'),L('por'),S('b','o')]},
 esNumero:     {cat:'operators', shape:'boolean', spec:[S('a','5'),L('¿es un número?')]},
 redondearA:   {cat:'operators', shape:'reporter', spec:[L('redondear'),S('a','3.14159'),L('a'),N('n',2),L('decimales')]},

/* ---------------- VARIABLES ---------------- */
 fijarVar:     {cat:'variables', shape:'stack', spec:[L('fijar'),M('v',['@vars']),L('a'),S('val','0')]},
 cambiarVar:   {cat:'variables', shape:'stack', spec:[L('cambiar'),M('v',['@vars']),L('por'),N('val',1)]},
 mostrarVar:   {cat:'variables', shape:'stack', spec:[L('mostrar variable'),M('v',['@vars'])]},
 esconderVar:  {cat:'variables', shape:'stack', spec:[L('esconder variable'),M('v',['@vars'])]},
 leerVar:      {cat:'variables', shape:'reporter', spec:[M('v',['@vars'])]},
 anadirLista:  {cat:'variables', shape:'stack', spec:[L('añadir'),S('val','cosa'),L('a'),M('l',['@listas'])]},
 borrarLista:  {cat:'variables', shape:'stack', spec:[L('borrar todo de'),M('l',['@listas'])]},
 elemLista:    {cat:'variables', shape:'reporter', spec:[L('elemento'),N('i',1),L('de'),M('l',['@listas'])]},
 largoLista:   {cat:'variables', shape:'reporter', spec:[L('largo de'),M('l',['@listas'])]},
 borrarElem:   {cat:'variables', shape:'stack', spec:[L('borrar elemento'),N('i',1),L('de'),M('l',['@listas'])]},
 insertarEn:   {cat:'variables', shape:'stack', spec:[L('insertar'),S('val','cosa'),L('en la posición'),N('i',1),L('de'),M('l',['@listas'])]},
 reemplazarEn: {cat:'variables', shape:'stack', spec:[L('reemplazar elemento'),N('i',1),L('de'),M('l',['@listas']),L('por'),S('val','cosa')]},
 listaContiene:{cat:'variables', shape:'boolean', spec:[M('l',['@listas']),L('contiene'),S('val','cosa'),L('?')]},
 posEnLista:   {cat:'variables', shape:'reporter', spec:[L('posición de'),S('val','cosa'),L('en'),M('l',['@listas'])]},
 elemAzar:     {cat:'variables', shape:'reporter', spec:[L('elemento al azar de'),M('l',['@listas'])]},
 listaComoTexto:{cat:'variables', shape:'reporter', spec:[L('unir'),M('l',['@listas']),L('con'),T('sep',', ')]},

/* ---------------- LÁPIZ (extensión) ---------------- */
 borrarLapiz:  {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('borrar todo')]},
 bajarLapiz:   {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('bajar lápiz')]},
 subirLapiz:   {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('subir lápiz')]},
 colorLapiz:   {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('fijar color'),C('col','#4c97ff')]},
 grosorLapiz:  {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('fijar grosor'),N('v',3)]},
 sello:        {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('sellar')]},
 cambiarColorLapiz:{cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('cambiar color por'),N('v',10)]},
 cambiarGrosor:{cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('cambiar grosor por'),N('v',1)]},
 colorAzarLapiz:{cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('color al azar')]},
 transpLapiz:  {cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('fijar transparencia a'),N('v',0),L('%')]},
 dibujarCirculo:{cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('dibujar círculo radio'),N('r',30)]},
 dibujarPoligono:{cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('dibujar polígono de'),N('n',5),L('lados, tamaño'),N('t',50)]},
 escribirTexto:{cat:'myblocks', shape:'stack', ext:'lapiz', spec:[L('escribir'),T('txt','¡Hola!'),L('tamaño'),N('n',20)]}
};
function S(k,d=''){ return {t:'slot', k, d}; }

/* Orden de la paleta por categoría */
const PALETTE = {
 motion:['mover','girarD','girarI','irA','irAObj','deslizar','irADeslizando','moverHacia','apuntarA','apuntarHacia','apuntarObj','cambiarX','fijarX','cambiarY','fijarY','cambiarXY','rebotar','rebotarSuave','ponerEnBorde','estiloRot','posX','posY','direccion','distanciaXY'],
 looks:['decirPor','decir','pensarPor','pensar','cambiarDisfraz','siguienteDisfraz','disfrazAnterior','disfrazAzar','cambiarFondo','siguienteFondo','fondoAzar','cambiarTam','fijarTam','rebotarTam','cambiarEfecto','fijarEfecto','quitarEfectos','mostrar','esconder','parpadear','alFrente','cambiarCapas','numDisfraz','nombreDisfraz','numFondo','nombreFondo','tamano','estaVisible'],
 sound:['tocarSonidoHasta','tocarSonido','pararSonidos','tocarNota','tocarMelodia','tocarTambor','silencio','cambiarTono','fijarTono','tono','cambiarVol','fijarVol','volumen'],
 events:['alBandera','alTecla','alClicObjeto','alTocarObj','alFondo','alMayorQue','alCargar','alRecibir','enviar','enviarEsperar','mensajeRecibido'],
 control:['esperar','esperarFrames','repetir','porSiempre','repetirDesde','contador','si','siSino','siNoEntonces','esperarHasta','repetirHasta','mientras','detener','alClonar','crearClon','borrarClon'],
 sensing:['tocando','tocandoBorde','tocandoColor','clicEnMi','distanciaA','preguntar','respuesta','teclaPulsada','ratonAbajo','ratonX','ratonY','cronometro','reiniciarCrono','propiedadDe','anchoEscenario','altoEscenario','numObjetos','fechaActual','esMovil'],
 operators:['sumar','restar','multiplicar','dividir','potencia','azar','mayor','menor','igual','mayorIgual','menorIgual','distinto','entre','y','o','no','minimo','maximo','limitar','unir','letraDe','largoDe','contiene','mayusculas','reemplazar','esNumero','modulo','redondear','redondearA','mateDe'],
 variables:['fijarVar','cambiarVar','mostrarVar','esconderVar','leerVar','anadirLista','insertarEn','reemplazarEn','borrarElem','borrarLista','elemLista','elemAzar','posEnLista','largoLista','listaContiene','listaComoTexto'],
 myblocks:['borrarLapiz','bajarLapiz','subirLapiz','colorLapiz','cambiarColorLapiz','colorAzarLapiz','grosorLapiz','cambiarGrosor','transpLapiz','dibujarCirculo','dibujarPoligono','escribirTexto','sello']
};
